# Generated by Django 6.0.1 on 2026-02-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_manager_options_manager_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('hours', models.FloatField(default=0)),
                ('notes', models.TextField()),
                ('photos', models.ImageField(blank=True, null=True, upload_to='internship_photos/')),
            ],
        ),
    ]
