# Generated by Django 6.0.1 on 2026-02-28 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_achievement_project_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='management.manager'),
        ),
        migrations.AddField(
            model_name='internshiplog',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internship_logs', to='management.manager'),
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='management.manager'),
        ),
        migrations.AddField(
            model_name='tool',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='management.manager'),
        ),
    ]
