# Generated by Django 6.0.1 on 2026-02-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_manager_avatar_url_manager_bio_manager_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='role',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('shift_manager', 'Shift Manager')], default='shift_manager', max_length=20),
        ),
    ]
