# Generated by Django 6.0.1 on 2026-02-28 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_issuereport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshiplog',
            name='photos',
        ),
    ]
