# Generated by Django 6.0.1 on 2026-01-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_options_alter_project_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
