# Generated by Django 6.0.1 on 2026-01-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=200)),
                ('ranked', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('date_achieved', models.DateField()),
                ('proof_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
