# Generated by Django 6.0.1 on 2026-01-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0002_alter_achievement_options_alter_achievement_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='category',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
