# Generated by Django 6.0.1 on 2026-01-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={'verbose_name': 'Tool', 'verbose_name_plural': 'Tools'},
        ),
        migrations.AlterModelTable(
            name='tool',
            table='tools',
        ),
    ]
